apiVersion: v1
kind: Service
metadata:
  name: my-flask-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30005 
    targetPort: 80 
  selector:
    app: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dep
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: erzez/api_erez:1
        ports:
        - containerPort: 80
