apiVersion: apps/v1
kind: Deployment
metadata:
  name: shir-deployment
spec:
  selector:
    matchLabels:
      app: test
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: shir-d
        image: erzez/api_erez:1
        ports:
        - containerPort: 80
