apiVersion: v1
kind: Pod
metadata:
  name: podsecret
spec:
  containers:
  - name: podsecret
    image: ubuntu
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      defaultMode: 0600
